Controllers/HomeController.cs
using OnlineShoppingDemo2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingDemo2.Controllers
{
    public class HomeController : Controller
    {

        private DataContext db = new DataContext();

        public ActionResult Index()
        {

            var product = db.Products.ToList();
            return View(product);
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
       

           












    }
}

Controllers/ProductUserController.cs
using OnlineShoppingDemo2.Migrations;
using OnlineShoppingDemo2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace OnlineShoppingDemo2.Controllers
{
   
    public class ProductUserController : Controller
    {
        // GET: ProductUser
        private DataContext db = new DataContext();

        



        public ActionResult ShowDetails(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }


       
       
        
       

       

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@model IEnumerable<OnlineShoppingDemo2.Models.Product>
@{
    ViewBag.Title = "Home Page";
}



<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-2 headingtag">
                <h1>Welcome to our<br>Online Shopping </h1>
                <p>Succcess is the new beginning into life </p>
              
            </div>
            <div class="col-2 topImage">
                <img src="https://cdn.pixabay.com/photo/2015/08/25/11/50/shop-906722__480.jpg" alt="" width="100%">
            </div>
        </div>
    </div>
</div>









<div class="small-container">

    <h2 class="title">Mens Shop</h2>
    <div class="row">
        @foreach (var item in Model)
        {
            if (item.Categories.CateName == "Mens")
            {

                <div class="col-4">

                    <img src="../Images/@item.ImageUrl" alt="" width="200px" height="250px">
                    <h4>@item.Name</h4>
                    <p>@item.Price</p>

                    <a class="buttonDetails">@Html.ActionLink("Details", "ShowDetails", "ProductUser", new { id = item.Id, area = "" }, new { @class = "navbar-brand" })</a>
                </div>
            }
        }
    </div>


    <h2 class="title">Kids Shop</h2>
    <div class="row">
        @foreach (var item in Model)
        {
            if (item.Categories.CateName == "Kids")
            {

                <div class="col-4">

                    <img src="../Images/@item.ImageUrl" alt="" width="200px" height="250px">
                    <h4>@item.Name</h4>
                    <p>@item.Price</p>

                    @Html.ActionLink("Details", "ShowDetails", "ProductUser", new { id = item.Id, area = "" }, new { @class = "navbar-brand" })
                </div>
            }
        }
    </div>

    <h2 class="title">Womens Shop</h2>
    <div class="row">
        @foreach (var item in Model)
        {
            if (item.Categories.CateName == "Womens")
            {

                <div class="col-4">

                    <img src="../Images/@item.ImageUrl" alt="" width="200px" height="250px">
                    <h4>@item.Name</h4>
                    <p>@item.Price</p>

                    @Html.ActionLink("Details", "ShowDetails", "ProductUser", new { id = item.Id, area = "" }, new { @class = "navbar-brand" })
                </div>
            }
        }
    </div>
</div>